# Generated by Django 5.2.5 on 2025-08-12 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdesign',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customdesign',
            name='price',
        ),
        migrations.RemoveField(
            model_name='customdesign',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customdesign',
            name='title',
        ),
        migrations.AddField(
            model_name='customdesign',
            name='framed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customdesign',
            name='design_file',
            field=models.FileField(upload_to='custom_designs/'),
        ),
        migrations.AlterField(
            model_name='customdesign',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customdesign',
            name='size',
            field=models.CharField(choices=[('A5', 'A5 (14.8 × 21 cm)'), ('A4', 'A4 (21 × 29.7 cm)'), ('A3', 'A3 (29.7 × 42 cm)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customdesign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
